import React, { useEffect } from "react";

const LayeredBoxes = ({
  updateFillCount,
  fillColors,
  onFill,
  preview = false,
  svgProps = {},
}) => {
  const paths = [
    <rect
      x="2.5"
      y="2.5"
      width="689"
      height="689"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="26.5"
      y="24.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="26.5"
      y="134.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="26.5"
      y="244.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="26.5"
      y="354.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="26.5"
      y="464.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="26.5"
      y="574.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="136.5"
      y="24.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="136.5"
      y="134.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="136.5"
      y="244.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="136.5"
      y="354.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="136.5"
      y="464.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="136.5"
      y="574.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="246.5"
      y="24.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="246.5"
      y="134.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="246.5"
      y="244.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="246.5"
      y="354.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="246.5"
      y="464.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="246.5"
      y="574.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="356.5"
      y="24.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="356.5"
      y="134.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="355.5"
      y="244.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="355.5"
      y="354.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="356.5"
      y="464.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="355.5"
      y="574.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="466.5"
      y="24.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="466.5"
      y="134.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="465.5"
      y="244.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="465.5"
      y="354.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="466.5"
      y="464.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="465.5"
      y="574.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="576.5"
      y="24.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="576.5"
      y="134.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="575.5"
      y="244.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="575.5"
      y="354.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="576.5"
      y="464.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="576.5"
      y="574.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="81.5"
      y="74.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="81.5"
      y="184.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="81.5"
      y="294.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="81.5"
      y="404.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="81.5"
      y="514.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="191.5"
      y="74.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="190.5"
      y="184.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="190.5"
      y="294.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="190.5"
      y="404.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="191.5"
      y="514.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="300.5"
      y="74.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="300.5"
      y="184.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="299.5"
      y="294.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="300.5"
      y="404.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="300.5"
      y="514.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="409.5"
      y="74.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="409.5"
      y="184.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="409.5"
      y="294.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="409.5"
      y="404.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="409.5"
      y="514.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="518.5"
      y="74.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="519.5"
      y="184.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="519.5"
      y="294.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="519.5"
      y="404.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <rect
      x="519.5"
      y="514.5"
      width="95"
      height="95"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
  ];

  useEffect(() => {
    if (!preview) updateFillCount(paths.length);
  }, []);

  function renderFillables() {
    if (preview) return paths;
    return paths.map((path, index) => {
      return React.cloneElement(path, {
        onClick: () => onFill(index),
        fill: fillColors[index],
      });
    });
  }

  return (
    <svg
      width="694"
      height="694"
      viewBox="0 0 694 694"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <rect width="694" height="694" fill="#E5E5E5" />
      {renderFillables()}
    </svg>
  );
};

export default LayeredBoxes;
