import React, { useEffect } from "react";

const Scales = ({
  updateFillCount,
  fillColors,
  onFill,
  preview = false,
  svgProps = {},
}) => {
  const paths = [
    <rect
      x="0.5"
      y="0.5"
      width="693"
      height="574"
      fill="white"
      stroke="black"
    />,
    <circle
      cx="62"
      cy="72"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="190"
      cy="72"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="318"
      cy="72"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="446"
      cy="72"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="574"
      cy="72"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="125"
      cy="105"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="253"
      cy="105"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="381"
      cy="105"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="509"
      cy="105"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="637"
      cy="105"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="62"
      cy="155"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="190"
      cy="155"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="318"
      cy="155"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="446"
      cy="155"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="574"
      cy="155"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="125"
      cy="197"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="253"
      cy="197"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="381"
      cy="197"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="509"
      cy="197"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="637"
      cy="197"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="62"
      cy="247"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="190"
      cy="247"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="318"
      cy="247"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="446"
      cy="247"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="574"
      cy="247"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="125"
      cy="281"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="253"
      cy="281"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="381"
      cy="281"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="509"
      cy="281"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="637"
      cy="281"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="62"
      cy="338"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="190"
      cy="338"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="318"
      cy="338"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="446"
      cy="338"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="574"
      cy="338"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="127"
      cy="372"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="255"
      cy="372"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="383"
      cy="372"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="511"
      cy="372"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="639"
      cy="372"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="62"
      cy="422"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="190"
      cy="422"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="318"
      cy="422"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="446"
      cy="422"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="574"
      cy="422"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="125"
      cy="453"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="253"
      cy="453"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="381"
      cy="453"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="509"
      cy="453"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="637"
      cy="453"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="62"
      cy="503"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="190"
      cy="503"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="318"
      cy="503"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="446"
      cy="503"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
    <circle
      cx="574"
      cy="503"
      r="47.5"
      fill="white"
      stroke="black"
      strokeWidth="5"
    />,
  ];

  useEffect(() => {
    if (!preview) updateFillCount(paths.length);
  }, []);

  function renderFillables() {
    if (preview) return paths;
    return paths.map((path, index) => {
      return React.cloneElement(path, {
        onClick: () => onFill(index),
        fill: fillColors[index],
      });
    });
  }

  return (
    <svg
      width="694"
      height="575"
      viewBox="0 0 694 575"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <rect width="694" height="575" fill="#E5E5E5" />
      {renderFillables()}
    </svg>
  );
};

export default Scales;
